name: 'Check Links'
on:
  workflow_dispatch:
  push:
    paths-ignore:
    - './docs/agc.md'
    - './docs/Genomics_Workflows.md'
  schedule:
    - cron: '0 0 1 */3 *'

jobs:
  link_check:
    name: 'Link Check'
    uses: STRIDES/NIHCloudLab/.github/workflows/check-links.yaml@main
    with:
      repo_link_ignore_list: ""
