name: 'Check Links'
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 1 */3 *'

jobs:
  link_check:
    name: 'Link Check'
    uses: STRIDES/NIHCloudLab/.github/workflows/check-links.yaml@main
    with:
      repo_link_ignore_list: "https://REPLACE_WITH_YOUR_IPv4_ADDRESS:8080,https://iam.nih.gov"
