name: Check Links

on:
  push:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        npm install -g markdown-link-check
        npm install -g html-proofer

    - name: Check links in Markdown files
      run: markdown-link-check --config .markdown-link-check.yaml $(find . -name "*.md" -not -path "./node_modules/*")

    - name: Check links in HTML files
      run: htmlproofer ./ --allow-hash-href --check-html --http-status-ignore "999"
